### ISSUE TITLE
Original name is truncated in console when renaming video with spaces

### ISSUE THREAD

**Issue by dexeonify** [Kayizoku/mpv-rename#3]
### Steps to reproduce
1. Open a video file with spaces in its name, like `blank video with spaces.mp4`
2. Rename the video to, for example, `blank video.mp4`
3. Open the console and observe rename.lua's log message.

### Actual result
```
[rename] renaming 'spaces.mp4' to 'blank video.mp4'
```
The original name is truncated.

### Expected result
```
[rename] renaming 'blank video with spaces.mp4' to 'blank video.mp4'
```
The original name should not be truncated.

Just some minor nuisance, it doesn't affect functionality at all.

**Comment by dexeonify** [comment]
Changing `%a*` to `.*` would probably work, but I am aware that `.*` is notorious for being horrible in performance.
https://github.com/Kayizoku/mpv-rename/blob/5f637547a1655c836ac777909d8981f0f13acee1/Rename.lua#L15

**Comment by Kayizoku** [comment]
Thank you, the bug has been solved in the latest commit.
